# Generated by Django 6.0.2 on 2026-02-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, help_text='Faculty or school name.', max_length=100, verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates administrative privileges (different from staff status).', verbose_name='Admin status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, help_text='6-20 character student identification.', max_length=20, null=True, unique=True, verbose_name='Student ID'),
        ),
    ]
