# Generated by Django 5.2.2 on 2025-08-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_calendar_sync_enabled_and_more'),
    ]

    operations = [
        # Announcement table already exists from booking 0001 in the canonical
        # migration history. Keep this migration as a no-op for compatibility
        # with branches that previously introduced it separately.
    ]
