# Generated by Django 5.2.2 on 2025-08-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_add_announcement_table'),
    ]

    operations = [
        # Canonical migration 0001 already contains the shortened index names.
        # Keep this migration as a no-op for compatibility with alternate
        # migration histories.
    ]
