# Generated by Django 5.2.2 on 2025-10-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_rename_announcement_active_show_until_idx_announcemen_is_acti_13e55a_idx_and_more'),
    ]

    operations = [
        # room_number is already created in booking.0001_initial in the
        # canonical migration history. Keep this migration as a no-op to avoid
        # duplicate-column failures on fresh MySQL databases.
    ]
