# Generated by Django 4.2.7 on 2026-03-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_room_capacity_policy_and_booking_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomOccupiedTimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rule name for admin reference', max_length=120)),
                ('rule_type', models.CharField(choices=[('fixed', 'Fixed Date'), ('recurring_weekly', 'Recurring Weekly')], default='fixed', help_text='Whether this is fixed for one date or recurring weekly', max_length=20)),
                ('fixed_date', models.DateField(blank=True, help_text='Date for fixed rule', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Optional start date for recurring rule validity', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Optional end date for recurring rule validity', null=True)),
                ('weekdays', models.CharField(blank=True, help_text='Comma-separated weekdays for recurring rule: 0=Mon ... 6=Sun', max_length=20)),
                ('start_time', models.TimeField(help_text='Occupied start time')),
                ('end_time', models.TimeField(help_text='Occupied end time')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(help_text='Room this occupied period applies to', on_delete=django.db.models.deletion.CASCADE, related_name='occupied_rules', to='booking.room')),
            ],
            options={
                'verbose_name': 'Room Occupied Time Rule',
                'verbose_name_plural': 'Room Occupied Time Rules',
                'db_table': 'room_occupied_time_rules',
                'ordering': ['room', 'rule_type', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='roomoccupiedtimerule',
            index=models.Index(fields=['room', 'is_active'], name='room_occupi_room_id_4de49e_idx'),
        ),
        migrations.AddIndex(
            model_name='roomoccupiedtimerule',
            index=models.Index(fields=['rule_type', 'fixed_date'], name='room_occupi_rule_ty_c8353e_idx'),
        ),
    ]
